server:
  port: 20000

spring:
  application:
    name: IM-auth
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/IM
  redis:
    host: 101.132.35.66
    port: 6379
    password: xiaohu
    database: 0
    timeout: 120000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: -1

kni4j:
  title: 消息服务
  version: 1.0.0
  license: I And You
  licenseUrl: www.baidu.com
  basePackage: com.xiaohu.message.controller